#!/bin/bash
# Script to run all days code at onc step.
echo day1
node day1/partOne.js
node day1/partTwo.js
echo “”
echo “”
echo day2
node day2/partOne.js
node day2/partTwo.js
echo “”
echo “”
echo day3
node day3/partOne.js
node day3/partTwo.js
echo “”
echo “”
echo day4
node day3/partOne.js
node day3/partTwo.js
echo “”
echo “”
echo day5
node day5/partOne.js
node day5/partTwo.js
echo “”
echo “”
echo day6
node day6/partOne.js
node day6/partTwo.js
echo “”
echo “”
echo day7
node day7/partOne.js
node day7/partTwo.js
echo “”
echo “”
echo day8
node day8/partOne.js
node day8/partTwo.js
echo “”
echo “”
echo day9
node day9/partOne.js
node day9/partTwo.js
echo “”
echo “”
echo day10
node day10/partOne.js
node day10/partTwo.js
echo “”
echo “”
echo day11
node day11/partOne.js
node day11/partTwo.js
echo “”
echo “”
echo day12
node day12/partOne.js
node day12/partTwo.js
echo “”
echo “”